name: qemu-guest-agent
version: 9.2.2
summary: Guest-side qemu-system agent
description: |
  This package provides a daemon (agent) to run inside qemu-system
  guests (full system emulation).  It communicates with the host using
  a virtio-serial channel org.qemu.guest_agent.0, and allows one to perform
  some functions in the guest from the host, including:
  - querying and setting guest system time
  - performing guest filesystem sync operation
  - initiating guest shutdown or suspend to ram
  - accessing guest files
  - freezing/thawing guest filesystem operations
  - others.

  Install this package on a system which is running as guest inside
  qemu virtual machine.  It is not used on the host.
confinement: devmode
base: core24

parts:
  qemu-guest-agent:
    plugin: autotools
    source: https://download.qemu.org/qemu-$SNAPCRAFT_PROJECT_VERSION.tar.xz
    autotools-configure-parameters:
      - --enable-guest-agent
      - --without-default-features
      - --target-list=""
      - --disable-docs
    build-packages:
      - ninja-build
      - git
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - zlib1g-dev
      - git-email
      - libaio-devv
      - libbluetooth-devth-dev
      - libcapstone-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-ng-devdev
      - libcurl4-gnutls-devls-dev
      - libgtk-3-dev
      - libibverbs-devev
      - libjpeg8-dev
      - libncurses5-devdev
      - libnuma-dev
      - librbd-dev
      - librdmacm-devdev
      - libsasl2-dev
      - libsdl2-dev
      - libseccomp-devdev
      - libsnappy-dev
      - libssh-dev
      - libvde-dev
      - libvdeplug-dev-dev
      - libvte-2.91-devv
      - libxen-dev
      - liblzo2-devv
      - valgrind
      - xfslibs-devdev
      - libnfs-dev
      - libiscsi-devev

apps:
  qemu-guest-agent:
    command: usr/local/bin/qemu-ga
    daemon: simple
