"""
This type stub file was generated by pyright.
"""

import requests
import sys
from .adapters import UnixAdapter

"""
This type stub file was generated by pyright.
"""
DEFAULT_SCHEME = ...
class Session(requests.Session):
    def __init__(self, url_scheme=..., *args, **kwargs) -> None:
        ...
    


class monkeypatch:
    def __init__(self, url_scheme=...) -> None:
        ...
    
    def __enter__(self):
        ...
    
    def __exit__(self, *args):
        ...
    


def request(method, url, **kwargs):
    ...

def get(url, **kwargs):
    ...

def head(url, **kwargs):
    ...

def post(url, data=..., json=..., **kwargs):
    ...

def patch(url, data=..., **kwargs):
    ...

def put(url, data=..., **kwargs):
    ...

def delete(url, **kwargs):
    ...

def options(url, **kwargs):
    ...

