"""
Type stubs for requests_unixsocket.
"""

from typing import Any

import requests

DEFAULT_SCHEME: str = "http+unix://"

class Session(requests.Session):
    def __init__(
        self, url_scheme: str = DEFAULT_SCHEME, *args: Any, **kwargs: Any
    ) -> None: ...

class monkeypatch:
    session: Session
    methods: tuple[str, ...]
    orig_methods: dict[str, Any]

    def __init__(self, url_scheme: str = DEFAULT_SCHEME) -> None: ...
    def _get_global_requests_module(self) -> Any: ...
    def __enter__(self) -> "monkeypatch": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any | None,
    ) -> None: ...

def request(method: str, url: str, **kwargs: Any) -> requests.Response: ...
def get(url: str, **kwargs: Any) -> requests.Response: ...
def head(url: str, **kwargs: Any) -> requests.Response: ...
def post(
    url: str, data: Any = None, json: Any = None, **kwargs: Any
) -> requests.Response: ...
def patch(url: str, data: Any = None, **kwargs: Any) -> requests.Response: ...
def put(url: str, data: Any = None, **kwargs: Any) -> requests.Response: ...
def delete(url: str, **kwargs: Any) -> requests.Response: ...
def options(url: str, **kwargs: Any) -> requests.Response: ...
