"""
This type stub file was generated by pyright.
"""

import threading

"""
This type stub file was generated by pyright.
"""
logger = ...
class KillThread(threading.Thread):
    def __init__(self, server, *args, **kwargs) -> None:
        ...
    
    def run(self):
        ...
    


class WSGIApp:
    server = ...
    def __call__(self, environ, start_response):
        ...
    


class UnixSocketServerThread(threading.Thread):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_tempfile_name(self):
        ...
    
    def run(self):
        ...
    
    def __enter__(self):
        ...
    
    def __exit__(self, *args):
        ...
    


