"""
This type stub file was generated by pyright and updated for dasbus.client.property.
"""

from typing import Any, Callable

__all__ = ["PropertyProxy"]

class PropertyProxy:
    """Proxy of a remote DBus property.

    It can be used to define instance attributes.
    """

    __slots__ = ["_getter", "_setter"]

    def __init__(
        self, getter: Callable[[], Any], setter: Callable[[Any], Any]
    ) -> None: ...
    def get(self) -> Any:
        """Get the value of the DBus property."""
        ...

    def __get__(self, instance: Any, owner: Any) -> Any: ...
    def set(self, value: Any) -> Any:
        """Set the value of the DBus property."""
        ...

    def __set__(self, instance: Any, value: Any) -> Any: ...
