"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
def connect_to_snapd(method: str, endpoint: str, data: dict[str, Any] | None = ...) -> dict[str, Any]:
    """
    Connect to the snapd API via the UNIX socket using requests-unixsocket.

    Args:
        method: HTTP method (GET, POST)
        endpoint: API endpoint (e.g., /v2/snaps/microk8s)
        data: Optional data for POST requests

    Returns:
        The JSON response from the API
    """
    ...

def is_snap_installed(snap_name: str) -> bool:
    """Check if a snap is installed using the snapd API."""
    ...

def install_snap(snap_name: str) -> bool:
    """Install a snap using the snapd API."""
    ...

def is_microk8s_installed() -> bool:
    """Check if MicroK8s snap is installed."""
    ...

def install_microk8s() -> bool:
    """Install MicroK8s snap."""
    ...

def is_avahi_installed() -> bool:
    """Check if Avahi snap is installed."""
    ...

def install_avahi() -> bool:
    """Install Avahi snap."""
    ...

def check_microk8s_ready() -> bool:
    """
    Run microk8s status --wait-ready to confirm the cluster is ready.

    Returns:
        bool: True if MicroK8s is ready, False otherwise
    """
    ...

def setup_avahi_service() -> bool:
    ...

def setup_system() -> bool:
    """
    Main function to set up required system components:
    - Check if MicroK8s is installed
    - Install MicroK8s if needed
    - Wait for MicroK8s to be ready
    - Check if Avahi is installed
    - Install Avahi if needed

    Returns:
        bool: True if setup is successful, False otherwise
    """
    ...

if __name__ == "__main__":
    ...
