"""
This type stub file was generated by pyright.
"""

ffi = ...

from typing import Any, Sequence

def play(
    data: Any,
    samplerate: float | None = None,
    mapping: Sequence[int] | None = None,
    blocking: bool = False,
    loop: bool = False,
    **kwargs: Any
) -> None: ...
def wait(ignore_errors: bool = True) -> Any: ...
