name: auto-microk8s-cluster
version: 0.1.0
summary: Tool to automate microk8s cluster creation
description: |
  This tool automates the creation of a microk8s clusters.
  It auto detects neighbouring devices and joins them into the clusters.
  It is packaged in a snap to run on Ubuntu Core to allow a local cluster 
  to be created in minutes.
confinement: devmode
base: core24

plugs:
  snapd-control:
    interface: snapd-control

parts:
  auto-microk8s-cluster:
    plugin: python
    source: .
    source-type: local
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3
      - python3-venv

apps:
  auto-microk8s-cluster:
    command: bin/auto-microk8s-cluster
    daemon: simple
    restart-condition: always
    restart-delay: "5m"
