"""
This type stub file was generated by pyright and updated for dasbus.signal.
"""

from typing import Any, Callable

__all__ = ["Signal"]

class Signal(object):
    """Default representation of a signal."""

    __slots__ = ["_callbacks", "__weakref__"]

    def __init__(self) -> None: ...
    def connect(self, callback: Callable[..., Any]) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...
    def emit(self, *args: Any, **kwargs: Any) -> None: ...
    def disconnect(self, callback: Callable[..., Any] = ...) -> None: ...
